### ISSUE TITLE
karakeep-web docker container fails to start correctly after update 0.26.0 to 0.27.0

### ISSUE THREAD

**Issue by thegilm** [karakeep-app/karakeep#1932]
### Describe the Bug

After the update from 0.26.0 to 0.27.0 the **karakeep-web** container comes up with an error. 

Complete log from the container:

```s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service init-db-migration: starting
Running db migration script
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
file:///db_migrations/index.js:7854
      throw new DrizzleError({ cause: err, message: `Failed to run the query '${staticQuery.sql}'` });
            ^
DrizzleError: Failed to run the query '
UPDATE `user` SET
  `bookmarkClickAction` = (
    SELECT `bookmarkClickAction` FROM `userSettings` WHERE `userSettings`.`userId` = `user`.`id`
  ),
  `archiveDisplayBehaviour` = (
    SELECT `archiveDisplayBehaviour` FROM `userSettings` WHERE `userSettings`.`userId` = `user`.`id`
  ),
  `timezone` = (
    SELECT `timezone` FROM `userSettings` WHERE `userSettings`.`userId` = `user`.`id`
  );'
    at BetterSQLiteSession.run (file:///db_migrations/index.js:7854:13)
    at SQLiteSyncDialect.migrate (file:///db_migrations/index.js:5712:21)
    ... 4 lines matching cause stack trace ...
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5) {
  cause: SqliteError: NOT NULL constraint failed: user.bookmarkClickAction
      at PreparedQuery.run (file:///db_migrations/index.js:7969:22)
      at BetterSQLiteSession.run (file:///db_migrations/index.js:7852:74)
      at SQLiteSyncDialect.migrate (file:///db_migrations/index.js:5712:21)
      at migrator_migrate (file:///db_migrations/index.js:2197:14)```

It looks like the migration script fails to update the USER table.
I'm using a portainer stack and have the KARAKEEP_VERSION set to 'release' in the stack.env

### Steps to Reproduce

I updated the app via portainer stack. 

1. stop the karakeep stack
2. go to stack editor tab
3. hit button "Update the stack"
4. check "Re-pull image and redeploy"
5. Hit the "Update" button

### Expected Behaviour

All three containers start up without errors.

### Screenshots or Additional Context

_No response_

### Device Details

_No response_

### Exact Karakeep Version

0.27.0

### Have you checked the troubleshooting guide?

- [x] I have checked the troubleshooting guide and I haven't found a solution to my problem

**Comment by MohamedBassem** [comment]
this has been fixed in https://github.com/karakeep-app/karakeep/issues/1919 which id available in the nightly build. Changing your karakeep version to “latest” should hopefully fix it

**Comment by thegilm** [comment]
Thanks for the response. I must have missed the other ticket, sorry about that! 
Gonna try again later then,
as of right now 'latest' doesn't fix it for me.

**Comment by MohamedBassem** [comment]
The fix has been released in 0.27.1. Pretty sure it'll fix your issue
